from . import as_hr_planilla_suedos
from . import as_planilla_sueldo_pdf
from . import as_planilla_tributaria
from . import as_planilla_tributaria_doc_pdf
from . import as_planilla_afp_doc_pdf
from . import as_planilla_patronal
from . import as_planilla_pago_prevision
from . import as_planilla_pago_futuro
from . import as_hr_planilla_suedos_v2
from . import as_hr_planilla_aguinaldo