# -*- coding: utf-8 -*-
{
    'name': 'AhoraSoft REPORTES de inventario',
    'version': '1.4.2',
    'category': 'Stock',
    'author': 'Ahorasoft',
    'summary': 'Customized Warehouse Management for Bolivia',
    'website': 'http://www.ahorasoft.com',
    'depends': [
        'base',
        'base_setup',
        'stock',
        'sale',
        'product',
        "purchase_stock",
        'sale_management',
        'report_xlsx',
        'purchase',
    ],
    'data': [
       'security/ir.model.access.csv',
        'wizard/as_kardex_productos_wiz.xml',
        'views/as_sale_order.xml',
        'views/as_stock_picking.xml',
        'wizard/as_reporte_existencias_pdf.xml',
        'views/as_format_report.xml',
        #'wizard/as_product_import.xml',
        'wizard/as_kardex_variantes_wiz.xml',
        #'report/as_salida_inventario.xml',
        'wizard/as_salidas_inventario_wiz_view.xml',
        'views/as_stock_picking_report.xml',
        'views/report/as_stock_picking_report.xml',
        'report/as_reporte_existencias.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}