from . import as_planilla_sueldos
from . import as_planilla_tributaria
from . import as_planilla_apf
from . import as_planilla_patronal
from . import as_planilla_sueldos_txt
from . import as_planilla_pago_prevision
from . import as_planilla_pago_futuro
from . import as_planilla_sueldos_v2
from . import as_planilla_aguinaldo
from . import as_payment_bonus
from . import as_payment_terceros