from . import hr_expense
from . import as_request_materials
from . import as_stock_picking
from . import as_viaticos
from . import hr_contract
from . import as_presupuesto
from . import as_purchase_order
from . import as_account_analytic_line
from . import as_project_task
from . import as_plantillas_project
from . import as_crossover_budget
from . import hr_employee
from . import as_gestion_viaje
from . import as_sale_order
from . import as_payment_multi
from . import as_res_users
from . import as_solicitud_viaticos
from . import as_hr_leave