from . import as_siat_codigo_sistema
from . import as_siat_sucursal
from . import as_siat_point_sale
from . import as_siat_catalogos
from . import as_res_partner
from . import res_users
from . import as_siat_endpoint
from . import as_siat_log
from . import as_res_config_setting
from . import as_siat_utility
from . import as_account_move
from . import as_product_template
from . import as_res_currency
from . import as_cafc
from . import as_send_massive_invoices