# -*- coding: utf-8 -*-
{
    'name': 'AhoraSoft Contabilidad Boliviana',
    'version': '1.2.9',
    'category': 'purchase',
    'author': 'Ahorasoft',
    'summary': 'customizacion para importaciones en compra',
    'website': 'http://www.ahorasoft.com',
    'depends': [
        'account',
        'base_setup',
        'stock',
        'journal_sequence',
        'account_reports',
        'fleet',
    ],
    'data': [
        # 'security/as_group_view.xml',
        'security/ir.model.access.csv',
        'views/as_tipo_retencion.xml',
        'views/as_res_company_view.xml',
        'views/as_account_move_campos.xml',
        'wizard/as_account_move_cuentas_pagar_proveedor.xml',
        'wizard/as_account_move_estado_cuentas_resumen_detallado.xml',
        'wizard/as_account_move_estado_cuentas_resumen.xml',
        'views/as_account_move_cuentas_por_pagar.xml',
        'wizard/as_print_comprobantes.xml',
        'wizard/as_regenerar_secuencia.xml',
        'views/as_report_format.xml',
        'views/report/as_report_account_move.xml',
        'views/as_account_move.xml',
        'views/as_account_journal.xml',
        
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}