# -*- coding: utf-8 -*-
{
    'name': 'AhoraSoft Modulo de Importar multiples compras en Importaciones',
    'version': '14.1.1',
    'category': 'purchase',
    'author': 'Ahorasoft',
    'summary': 'Customized purchase Management for Bolivia',
    'website': 'http://www.ahorasoft.com',
    'depends': [
        'base',
        'base_setup',
        'stock',
        'product',
        "purchase_stock",
        'purchase',
        'stock_landed_costs',
        'stock_account',
        'as_bo_purchase_invoice',
        'as_bo_purchase_import',
        'as_bo_product_stock',
        'as_bo_accounting',
    ],
    'data': [
        # 'security/as_group_view.xml',
        # 'security/ir.model.access.csv',
        'views/as_stock_landed_cost.xml',
        'views/as_purchase.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}