# -*- coding: utf-8 -*-
{
    'name': 'AhoraSoft Importacion en Compras',
    'version': '1.3.0',
    'category': 'purchase',
    'author': 'Ahorasoft',
    'summary': 'customizacion para importaciones en compra',
    'website': 'http://www.ahorasoft.com',
    'depends': [
        'base',
        'base_setup',
        'stock',
        'product',
        "purchase_stock",
        'purchase',
        'stock_landed_costs',
        'stock_account',
        'as_bo_purchase_invoice',
        'as_bo_configuration',
        'as_bo_purchase',
        'as_bo_invoice_client',
        # 'l10n_latam_invoice_document',
        # 'as_warehouse',
    ],
    'data': [
        'security/as_group_view.xml',
        'security/ir.model.access.csv',
        'views/as_stock_landed_cost.xml',
        'views/as_purchase.xml',
        'views/as_product_template.xml',
        'views/as_format_report.xml',
        'views/as_template_purchase_cost.xml',
        # 'views/res_config_settings_views.xml',
        'views/report/as_report_resumen_gastos.xml',
        # 'views/as_tipo_retencion.xml',
        'views/as_account_journal.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}