# -*- coding: utf-8 -*-
{
    'name': 'Recursos Humanos Localizacion Boliviana',
    'version': '1.5.5',
    'category': 'hr',
    'author': 'Ahorasoft',
    'summary': 'Customizado del Modulo HR',
    'website': 'http://www.ahorasoft.com',
    'depends': [
        'hr','hr_contract','hr_payroll','hr_payroll_account','as_bo_configuration','account','as_bo_hr_ausencias','as_bo_tesoreria',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/as_project_security.xml',
        'wizard/as_payment_terceros.xml',
        'views/as_hr_employee.xml',
        'views/as_hr_employee_afp.xml',
        'views/as_hr_payslip.xml',
        'views/as_hr_payslip_run.xml',
        'wizard/as_planilla_sueldos.xml',
        'views/as_report_format.xml',
        'report/as_planilla_tributaria_doc_pdf.xml',
        'wizard/as_planilla_afp.xml',
        'views/as_hr_smn.xml',
        'views/as_hr_lugar_trabajo.xml',
        'views/as_hr_contract.xml',
        'views/report/as_hr_papeleta.xml',
        'views/report/as_hr_finiquito.xml',
        'views/report/as_report_retroactivo.xml',
        'views/as_hr_worked_days.xml',
        'views/as_hr_inputs.xml',
        'views/as_company.xml',
        'views/as_hr_salary_rule_list.xml',
        'views/as_payroll_account.xml',
        'wizard/as_planilla_patronal.xml',
        'views/as_hr_finiquito.xml',
        'report/as_planilla_afp_doc_pdf.xml',
        'report/as_planilla_sueldo_pdf.xml',
        'wizard/as_planilla_tributaria.xml',
        'wizard/as_planilla_sueldos_txt.xml',
        'wizard/as_planilla_pago_prevision.xml',
        'wizard/as_planilla_pago_futuro.xml',
        'wizard/as_planilla_sueldos_v2.xml',
        'wizard/as_planilla_aguinaldo.xml',
        'wizard/as_payment_bonus.xml',
        'views/as_indicadores.xml',
        'views/as_hr_menu.xml',
        'views/as_sucursal.xml',
        'views/as_resource_calendar.xml',
        'views/as_employee_category.xml',
        'views/as_account_account.xml',
        'data/as_payroll_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}