# -*- coding: utf-8 -*-
{
    'name': 'Facturación Cliente Localización Boliviana',
    'version': '1.2.2',
    'category': 'invoice',
    'author': 'Ahorasoft',
    'summary': 'Customized Warehouse Management for Bolivia',
    'website': 'http://www.ahorasoft.com',
    'depends': [
        'base',
        'base_setup',
        'account',
        'sale',
        'as_bo_invoice_report',
        'as_bo_accounting',
        'as_bo_tesoreria',
    ],
    'data': [
       'security/ir.model.access.csv',
        'views/as_config_menu.xml',
        'views/as_send_massive_invoices.xml',
        'views/as_siat_codigo_sistema.xml',
        'views/as_siat_catalogos.xml',
        'views/as_res_partner.xml',
        'views/res_users.xml',
        'views/as_siat_sucursal.xml',
        'views/as_siat_point_sale.xml',
        'views/as_siat_endpoint.xml',
        'views/as_siat_log.xml',
        'views/as_res_config_setting.xml',
        'views/as_product_template.xml',
        'data/as_siat_endpoint.xml',
        'data/as_siat_group.xml',
        'data/as_template_mail.xml',
        'views/as_account_move.xml',
        'views/as_res_currency.xml',
        'views/as_cafc.xml',
        'data/as_cron.xml',
        'wizard/as_account_move_reversal_view.xml',
        'wizard/as_anular_facturas.xml',
        'views/as_payment_multi.xml',
       
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}