# -- coding: utf-8 --
{
    'name' : "Ahorasoft SPECTROCOM correlacional",
    'version' : "3.0.9",
    'author'  : "Ahorasoft",
    'description': """
Webservice dummy SPECTROCOM
===========================

Custom module for Latproject
    """,
    'category' : "Uncategorized",
    'depends' : [
        "base_setup",
        "analytic",
        "portal",
        "digest",
        "base",
        "sale",
        "stock",
        "account",
        "product",
        "as_bo_assets",
        "hr",
        "as_bo_sales_reports",
        "product_brand",
        "as_bo_purchase_import",
        'purchase',
        'sale_subscription',
        'as_bo_assets_stock',
        'as_bo_invoice_report',
        'as_bo_purchase_invoice',
        'as_bo_tesoreria',
        'as_bo_invoice_auto',
        'as_bo_account_stock',
        ],
    'website': 'http://www.ahorasoft.com',
    'data' : [
            'security/ir.model.access.csv',
            'views/as_client_fields.xml',
            'wizard/as_duplicate_sale.xml',
            'views/as_sale_order.xml',
            'views/as_sequence.xml',
            'views/as_template_project.xml',
            'views/as_business_type.xml',
            'views/as_product_template.xml',
            'views/as_proposal_conditions.xml',
            'views/report/as_sale_report_templates.xml',
            'views/report/as_sale_report_templates_sst.xml',
            'views/as_report_format.xml',
            'views/as_template_image.xml',
            'views/as_instructive_sale.xml',
            'views/as_reporte_orden_de_trabajo.xml',
            'views/report/as_reporte_orden_de_trabajo.xml',
            'wizard/as_detalle_producto.xml',
            'wizard/as_stock_product.xml',
            'views/as_sale_order_inherit_view.xml',
            'views/as_view_sale_order_columnas.xml',
            'views/as_res_partner.xml',
            'views/report/as_sale_report_templates_bs.xml',
            'views/report/as_report_account_invoice.xml',
            'views/as_sale_prefactura.xml',
            'views/report/as_sale_prefactura.xml',
            'wizard/as_factura_wiz.xml',
            'wizard/as_facturas_pagadas_pendientes.xml',
            'wizard/as_mora_wiz.xml',
            'views/as_account_move.xml',
            'views/as_res_users.xml',
            'views/as_purchase_order.xml',
            'views/as_stock_picking.xml',
            'data/as_template_email.xml',
            'views/as_project_task.xml',
            'views/as_search_bar.xml',
            'views/as_account_journal.xml',
            'views/as_hr_salary_rule.xml',
            'views/as_stock_picking_columnas.xml',
            'views/as_res_config.xml',
             ],
    
    'demo' : [],
    'installable': True,
    'auto_install': False
}