from . import as_sale_order
from . import as_forma_pago
from . import as_res_partner
from . import as_tipo_cliente
from . import as_template_project
from . import as_business_type
from . import as_product_template
from . import as_proposal_conditions
from . import as_instructive_sale
from . import as_reporte_orden_trabajo_project
from . import as_analytic_account
from . import as_purchase_order
from . import as_view_sale_order_columnas
from . import as_project_project
from . import as_nits
from . import as_partner
from . import as_instructive_sale_2
from . import as_account_move
from . import as_res_users
from . import as_stock_picking
from . import as_project_task
from . import as_payment_multi
from . import as_account_journal
from . import as_sale_invoice
from . import as_hr_salary_rule
from . import as_res_config
from . import as_sale_subscription_template
from . import as_hr_payslip