from . import as_indicadores
from . import as_hr_employee
from . import as_hr_employee_apf
from . import as_hr_payslip
from . import as_hr_payslip_run
from . import as_hr_smn
from . import as_hr_contract
from . import as_hr_worked_days
from . import as_hr_inputs
from . import as_company
from . import as_hr_salary_rule_list
from . import as_payroll_account
from . import as_hr_finiquito
from . import as_resource_calendar
from . import as_hr_lugar_trabajo
from . import as_sucursal
from . import as_employee_category
from . import as_taxes_requests
from . import as_account_account