# -- coding: utf-8 --
{
    'name' : "Ahorasoft SPECTROCOM correlacional",
    'version' : "2.4.1",
    'author'  : "Ahorasoft",
    'description': """
Webservice dummy SPECTROCOM
===========================
Custom module for Latproject
    """,
    'category' : "Uncategorized",
    'depends' : [
        "base_setup",
        "analytic",
        "portal",
        "digest",
        "base",
        "sale",
        "hr",
        "hr_expense",
        "project",
        "purchase",
        "sale_project",
        "sale_timesheet",
        "product_brand",
        'base_user_role',
        'as_bo_tesoreria',
        'as_bo_purchase_approval',
        'as_bo_stock',
        ],
    'website': 'http://www.ahorasoft.com',
    'data' : [
        'security/ir.model.access.csv',
        'security/as_cancel.xml',
        'wizard/as_transfer_product.xml',
        'wizard/as_generate_desembolso.xml',
        'wizard/as_transfer_product_return.xml',
        'views/hr_expense_view.xml',
        'views/project_task_view.xml',
        'views/as_request_materials.xml',
        'views/as_sequence.xml',
        'views/as_viaticos.xml',
        'views/as_hr_contract_views.xml',
        'views/as_purchase_order.xml',
        'views/as_hr_timesheet_template.xml',
        'views/as_hr_timesheet.xml',
        'views/as_sale_order_nota_de_remision.xml',
        'views/report/as_sale_order_nota_remision.xml',
        'views/as_account_budget.xml',
        'views/as_plantillas_project.xml',
        'views/as_hr_employee.xml',
        'views/as_gestion_viaje.xml',
        'data/as_template_email.xml',
        'views/as_hr_expense_gastos.xml',
        'views/as_hr_leave.xml',
        'views/report/as_hr_expense_gastos.xml',
        'views/as_hr_expense_campos.xml',
        'views/as_stock_picking.xml',
        'views/as_sale_order.xml',
        'views/report/as_gestion_viaje.xml',
        'views/res_users.xml',
        'views/report/as_solicitud_viaticos.xml',

             ],
    'demo' : [],
    'installable': True,
    'auto_install': False
}